# Adds shadows to the dataset

import albumentations as A
import automold
import cv2
from matplotlib import pyplot as plt
from random import randint

def visualize(image):
    """Show an image"""
    plt.figure(figsize=(10, 10))
    plt.axis('off')
    plt.imshow(image)

path="path/to/generated/images/" #TODO: before running, update with path to images generated by "generate_imgset2"
shadow_dimension = 5
NUM_RECORDS = 21838

for pt_number in range(1, NUM_RECORDS):
    image = cv2.imread(path+"pt_"+str(pt_number)+".png")
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    roi = (0, 0, image.shape[1], image.shape[0])
    num_shadows = randint(1, 3)
    shadowy_image = automold.add_shadow(image, num_shadows, roi, shadow_dimension)
    shadowy_image = cv2.cvtColor(shadowy_image, cv2.COLOR_RGB2BGR)
    cv2.imwrite(path+"/shadow/pt_"+ str(pt_number)+".png", shadowy_image)
